name: Build libvips Windows Binaries

on:
  workflow_dispatch:

jobs:
  build_binaries:
    runs-on: ubuntu-latest # Or ubuntu-24.04

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the MXE build image
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      # --- DIAGNOSTIC STEPS (already correct indentation) ---
      - name: Debug Docker Environment
        run: |
          echo "Checking docker version:"
          docker --version || echo "Docker not found or version check failed"
          echo "Checking docker info:"
          docker info || echo "Docker info failed"
          echo "Checking PATH:"
          echo $PATH
          echo "Checking current user and groups:"
          id
          echo "Attempting a simple docker run (hello-world):"
          docker run --rm hello-world || echo "hello-world failed"

      # --- ORIGINAL FAILING STEP - CORRECTED INDENTATION ---
      - name: Run libvips MXE build
        run: | # <--- THIS IS THE CORRECT INDENTATION for 'run:'
          # Use 'bash -x' for verbose output of the script's execution
          # You might also want to temporarily remove the `\ ` (backslash space)
          # continuation characters to make the command single-line for clarity in logs,
          # though they are technically correct.
          docker run \
            --rm \
            -v "$(pwd):/src" \
            ghcr.io/${{ github.repository }}:latest \
            /bin/bash -xc "/src/build.sh" # Execute build.sh with verbose bash output

      - name: Upload Windows Binaries
        uses: actions/upload-artifact@v4
        with:
          name: libvips-windows-binaries
          path: ./releases/
