name: Build libvips Windows Binaries

on:
  workflow_dispatch:

jobs:
  build_binaries:
    runs-on: ubuntu-latest # Or ubuntu-24.04

    steps:        
      # - name: Remove conflicting containerd packages
      #   run: |
      #     sudo apt-get remove -y containerd containerd.io || true

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          sudo systemctl status docker
          docker version
          docker info
      
      # - name: Clean up and update
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get autoremove -y
    
      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io
      #     sudo systemctl start docker
      #     sudo usermod -aG docker $USER
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the MXE build image
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Debug Docker Environment
        run: |
          echo "Checking docker version:"
          docker --version || echo "Docker not found or version check failed"
          echo "Checking docker info:"
          docker info || echo "Docker info failed"
          echo "Checking PATH:"
          echo $PATH
          echo "Checking current user and groups:"
          id
          echo "Attempting a simple docker run (hello-world):"
          docker run --rm hello-world || echo "hello-world failed"

      - name: Ensure Docker in PATH
        run: |
          export PATH=$PATH:/usr/bin:/usr/local/bin
          command -v docker || { echo "docker not in PATH after export"; exit 1; }
          ./build.sh ...
      
      - name: Run build.sh
        run: |
          echo "PATH before running build.sh: $PATH"
          command -v docker || { echo "docker not in PATH"; exit 1; }
          ./build.sh ...

      - name: Upload Windows Binaries
        uses: actions/upload-artifact@v4
        with:
          name: libvips-windows-binaries
          path: ./releases/
