name: Build LibVips for Windows Release - all

on: workflow_dispatch

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest # Using a Linux runner as build-win66-mxe cross-compiles

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker (if not already available)
        # GitHub Actions runners usually have Docker pre-installed, but this ensures it.
        # You might not need this step explicitly, but it's good for clarity.
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker ${{ github.actor }}
          # Newgrp is needed to apply the group change immediately
          newgrp docker

      - name: Build LibVips (all --with-hevc)
        run: |
          ./build.sh all --with-hevc

      - name: Find generated artifacts
        id: find_artifacts
        run: |
          # The build.sh script places artifacts in the 'packaging' directory.
          # We need to find the specific zip file(s) to upload.
          # Assuming only one zip file is generated per build run,
          # or we want to upload all of them.
          ZIP_FILE=$(find packaging -name "vips-dev-*.zip" | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "No zip file found in 'packaging' directory!"
            exit 1
          fi
          echo "Found artifact: $ZIP_FILE"
          echo "ARTIFACT_PATH=$ZIP_FILE" >> $GITHUB_OUTPUT
          echo "ARTIFACT_NAME=$(basename $ZIP_FILE)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true # Set to true to create a draft release first
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_artifacts.outputs.ARTIFACT_PATH }}
          asset_name: ${{ steps.find_artifacts.outputs.ARTIFACT_NAME }}
          asset_content_type: application/zip
