name: test Build LibVips for Windows Release - all
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest # Using a Linux runner as build-win66-mxe cross-compiles

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Build LibVips (all --with-hevc)
      #   run: |
      #     # ./build.sh vips-all x86_64-w64-mingw32.shared --with-hevc
      #     ./build.sh vips-all --target x86_64-w64-mingw32.shared --with-hevc

      # - name: Upload all zips
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: vips-zips
      #     path: packaging/*.zip

      # - name: List zips to upload
      #   run: ls -l packaging/*.zip

      - name: Fetch all tags
        run: git fetch --tags

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view "${{ github.event.inputs.tag_name }}" &>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Debug release exists
        run: echo "Release exists ${{ steps.check_release.outputs.exists }}"
      
      - name: Create GitHub Release
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Release ${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload all zips to release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ github.event.inputs.tag_name }}
      #     files: packaging/*.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
